sasjs/adapter

src/SASViyaApiClient.ts, src/SASjs.ts, src/SessionManager.ts, src/utils/makeRequest.ts, src/utils/needsRetry.ts
Clean up after using a session, to minimise resource usage on the SAS server.
* Added `clearSession` method in `SessionManager`.
* Call `clearSession` after each job execution.
* Fixed linting errors.
* Removed redundant `sessionId` parameter as we have determined that sessions can't be reused.
=> feat(session-cleanup): delete a session after it has been used

src/SASjs.ts, src/utils/index.ts, src/utils/parseWeboutResponse.ts
When debug is on, response is between the `WEBOUTBEGIN<< and >>weboutEND<<`.
That is not a valid JSON so it triggered error while doing `JSON.parse()`.
Problem was on 3 places:
- Appending sasjs request
- executeJob
- executeComputeJob
Wrapping `JSON.parse()` with `try-catch` block and in `catch` block we parse response before passing it to `JSON.parse()`
=> fix: job definition debug log parse

src/SASViyaApiClient.ts, src/SessionManager.ts, src/types/Session.ts
* Added `try`/`catch` blocks to `executeScript`.
* When a 404 is caught, retry the job execution.
* When any other error is caught, pass it on to the caller.
* Check if a session has been inactive for longer than the timeout value.
* If a session has expired, discard it, create a fresh session and return.
* Else, return the original session.
=> fix(session-expiry-retry): retry job with new session on expiry

src/SASViyaApiClient.ts, src/SASjs.ts
* Changed public methods to take `contextName` instead of `contextId`.
* Fetch context by name and then use the `id` to delete it.
=> feat(delete-context): delete context by name

PULL_REQUEST_TEMPLATE.md, sasjs-tests/package-lock.json, sasjs-tests/package.json, sasjs-tests/src/testSuites/RequestData.ts, src/SASViyaApiClient.ts
Fixes https://github.com/sasjs/adapter/issues/97, https://github.com/sasjs/adapter/issues/98
When using the JES API approach, each file upload request and any immediate next request fails and is retried because the CSRF token is invalid. This causes a significant drop in performance due to the overhead involved in making the extra requests each time.
It turns out that the CSRF token used for most operations does not work for file upload, and the other way around.
So here's what fixes it:
* Maintain a separate CSRF token for file uploads.
* Use this token when a file upload request is made.
* For all other requests, use the normal token we always had.
* Fix failing tests in `sasjs-tests`.
* Bump adapter version.
Tests available at https://sas.analytium.co.uk/kriaco/sasjs-tests-jes
=> fix(jes-job-execution): prevent file upload requests failing with invalid CSRF token

src/SASViyaApiClient.ts
No related issue
In some function calls, access token hasn't been passed. So that was triggering errors when calling `request` from `CLI` with access token.
`accessToken` has been added to function call parameter.
---
=> Access token missed

src/SASViyaApiClient.ts, src/SessionManager.ts, src/utils/makeRequest.ts
To handle internal SAS error with status code `304` when requesting session status.
1. Handled internal SAS error in `SessionManager`.
2. Executed test scripts in `getExecutableContexts` method one after anather.
=> fix(session): add internal SAS error handler

src/types/ErrorResponse.ts
Name `body` ErrorResponse doesn't make much sense, changed it to `error`
=> fix: ErrorResponse body changed to error

sasjs-tests/src/testSuites/Basic.ts, src/SASjs.ts
Closes #117 
Fix for the viya login issue, after one login attempt, all other attempts would fail, with both valid and invalid credentials.
`getLoginForm` function fetches the login page, and takes data from it, that will be used in our login request. The most important piece is `CSRF token`.
Function was fetching the login page with login link that includes suffix `.do` and that works on first attempt but on the other attempts, that url is invalid. Solution was to use login link without `.do` all the time.
I took I chance and did small refactor, so now we have one call request less when doing a login procedure.
=> fix: viya login issue

src/SASViyaApiClient.ts
We need to display log and job status in case of failing job.
It will be passing job data back to cli
In promise reject, now passing complete data object that's needed in cli.
There's no such property `currentJob.error`
=> fix(job execute): details for failing job

.gitignore, PULL_REQUEST_TEMPLATE.md, package.json, webpack.config.js
https://github.com/sasjs/adapter/issues/160
Fix the build process to export type declarations for both browser and node versions of the adapter.
https://sas.analytium.co.uk/kriaco/sasjs-tests-build/#/
=> fix(*): export type declarations for node version of adapter

src/SASViyaApiClient.ts, src/types/Folder.ts
sasjs execute not working due to count of present items is greater than 20
=> fix: fetch all items of folder

src/SessionManager.ts
https://github.com/sasjs/cli/issues/317
Continue polling session status if session status is equal to `running` or an empty string.
=> fix(session-status): fixed stop polling session status

src/SASjs.ts
https://github.com/sasjs/cli/issues/302
Deploy services into a `services` subfolder rather than at the root of the `appLoc`.
Remove special case for `services` folder.
=> fix(deploy-service-pack): deploy services into 'services' subfolder

src/SASViyaApiClient.ts
https://github.com/sasjs/adapter/issues/202
Process relative and absolute paths the same way, so that relative paths with multiple nested folders can be specified with `sasjs request`.
Standardise how we process paths.
The only difference between absolute and relative paths now, is that we don't append the appLoc in the beginning for absolute paths.
=> fix(relative-paths): process relative and absolute paths the same way

package-lock.json, package.json
SASjs CLI unit tests don't pass with `isomorphic-fetch@3.0.0` that is why this dependency has been downgraded to `2.2.1`
Mocked:
Server:
=> chore(deps): rolled back isomorphic-fetch

src/SASViyaApiClient.ts, src/SessionManager.ts
Improve error handling in `startComputeJob` method to catch unhandled promise rejection in `sasjs flow execute` command.
1. Updated `executeScript` method.
Mocked:
Server:
=> fix(startComputeJob): improved error handling

.gitignore, src/request/RequestClient.ts
Handle unhandled promise rejection in `sasjs flow execute` command.
Added `catch` block in `handleError` method of `RequestClient`.
Mocked:
Server:
=> fix(RequestClient): improved handleError method

src/request/RequestClient.ts
Catch unhandled promise rejection in `startComputeJob` method.
=> fix(RequestClient): add catch block to authorize method

src/SASViyaApiClient.ts
For `unable to fetch job's log`, fetch session log, if session is failed or in stopped state.
Handled case where getting job info and unable to get it due to session failed/stopped.
mocked: 
server:
=> fix: fetch session log for session failed/stopped state

src/SASViyaApiClient.ts
https://github.com/sasjs/cli/issues/657
Continue polling regardless of HTTP errors on the request to get a job's state, until `MAX_POLL_COUNT` has been exceeded.
* If there is an error on the initial fetch of the job state, assume the job status to be `running`.
* If there is an error during polling for the job state, continue polling while assuming the job status to be `running`.
* In both cases, log a message to the console.
* If there is an error during polling and the `MAX_POLL_COUNT` has been exceeded, throw an error.
* Minor formatting changes due to Prettier version upgrade.
Tests are available at https://sas.analytium.co.uk/kriaco/sasjs-tests-poll
=> fix(job-state-poll): Continue poll regardless of errors

.git-hooks/commit-msg, package.json
Enable pre-commit git hook enforcing conventional commits.
1. Added `.git-hooks/commit-msg`.
2. Added `postinstall` script to `package.json`
=> feat(git): enabled git hook enforcing conventional commits

.git-hooks/commit-msg, src/request/RequestClient.ts, src/types/errors/SAS9AuthError.ts
No linked issues.
Fail with a descriptive error when invalid credentials are provided.
* Throw a `SAS9AuthError` when the redirected URL contains the string `sasAuthError`.
* Modify git hooks regex to allow numbers in commit prefix.
=> fix(sas9-support): Throw error when invalid credentials are supplied

sasjs-tests/README.md
adding makeErr service on sas9
=> fix: adding makeErr for SAS 9 in sajss-tests

webpack.config.js
Wix project package.
Removed `process` plugin from `nodeConfig`
=> fix(webpack): removed process plugin from nodeConfig

src/SAS9ApiClient.ts
No linked issue.
Force `_webout` output when executing arbitrary code on SAS9 to prevent STP errors.
* Added some lines of code at the end of the user's code to force `_webout` output.
```
I am currently in the process of adding more CLI tests here: https://github.com/sasjs/cli/tree/sas9-support
```
=> fix(sas9): force webout output when executing arbitrary code on SAS9

sasjs-tests/src/testSuites/Basic.ts, src/job-execution/JobExecutor.ts
#327 
provide correct values to SASWORK attribute in request.
modified code logic in appendRequest method in BaseJobExecutor class.
=> fix(*): SASWORK is not being parsed correctly

PULL_REQUEST_TEMPLATE.md
The previous merge broke the CLI build.  If quick fixes are needed, we should use alternative means, not the master branch.
=> chore(*): Update PULL_REQUEST_TEMPLATE.md

src/SASViyaApiClient.ts
closes #420
pass the debug parameter to correct section i.e. variable not argument
adding  _DEBUG: 131 to jobVariable object if debug is  true
=> fix: on viya when calling api pass debug parameter to correct section

package.json, src/SASViyaApiClient.ts, src/SessionManager.ts, src/request/RequestClient.ts
1. Handle server response with the status `304`.
2. Improve polling session status.
1. Overriden the range of valid response statuses in axios.
Mocked:
Server:
=> fix(session): fixed polling session state

.github/workflows/build.yml, package-lock.json, package.json, src/api/viya/pollJobState.ts, src/api/viya/spec/pollJobState.spec.ts
https://github.com/sasjs/cli/issues/587
When streaming logs:
* Use the given path as-is if it points to a file
* Generate a file path with a timestamp if the given path points to a folder.
* Added `isFolder` check when creating write stream.
* Added tests.
* Set minimum node version to 15.
=> fix(stream-log): use filepath if provided

src/FileUploader.ts
Fixes fileUploader [issue](https://github.com/sasjs/fileuploader/issues/2)
Parse debug response correctly.
- removed additional checks while deciding to parse debug response for `SASVIYA`
Mocked:
Server:
VIYA:
SAS 9:
=> fix(fileUploader): parsing debug response for SASVIYA

src/SASjs.ts, src/job-execution/WebJobExecutor.ts
#508
- fallback to default context name when passed context name is null/undefined or empty string while useComputeApi is false
- skip _contextname variable from api when passed context name is null/undefined or empty string while useComputeApi is undefined
- added check to see if context name is falsy value then fallback to default while useComputeApi is false
- added check to see if context name is falsy value then skip _contextname variable from apiUrl while useComputeApi is undefined
Mocked:
Server:
SAS Viya:
SAS 9:
=> fix: handle context name when it's undefined/null or empty string

package.json
[`typescript 4.4.2`](https://github.com/microsoft/TypeScript/releases/tag/v4.4.2) breaks `package:lib` script.
Pinned `typescript` dependency on version `4.3.5`
Mocked:
Server:
SAS VIYA:
SAS9:
VIYA:
SAS9:
=> chore(deps): pin typescript version to fix packaging

src/utils/parseViyaDebugResponse.ts
Fixes #554 
Fixing viya debug request returning null due to wrong content-type passed in request client.
Added parameter for content-type to be `plain/text`
Mocked:
Server:
=> fix: viya debug response null due to wrong content-type

sasjs-tests/src/testSuites/Basic.ts, src/job-execution/ComputeJobExecutor.ts, src/job-execution/JesJobExecutor.ts, src/job-execution/WebJobExecutor.ts
No issue to link.
- append resend requests before making login call
- append resend request for `SASVIYA` when `getJobUri` throw `LoginRequiredError`
- rearrange the order of execution of `loginCallback` and `appendWaitingRequest`
- added exception handling for `getJobUri`
Mocked:
Server:
SAS Viya:
SAS9:
SAS Viya:
SAS9:
=> fix: Job executor bugs

src/job-execution/WebJobExecutor.ts
No issue to link.
Parsing of response from SASJS server is fine when DEBUG is on but invalid parsing when DEBUG is off.
Added parsing of JSON-String to JSON when DEBUG is off.
=> fix: response from SASJS Server with/without debug on

src/SessionManager.ts, src/api/viya/pollJobState.ts, src/api/viya/spec/pollJobState.spec.ts, src/request/RequestClient.ts, src/test/RequestClient.spec.ts, src/test/SAS_server_app.ts, src/test/SessionManager.spec.ts
- Closes #604
- https://github.com/sasjs/cli/issues/1067 
Fix error handling logic.
- Changed `httpClient.defaults.validateStatus` to include `401`.
- Improved `handleError` method.
- Changed `doPoll` method.
=> Improve error handling and job/session state polling

src/request/SasjsRequestClient.ts
no issue to link
While `sasjs deploy` it breaks. 
Added check for window.
=> fix(sasjs): restrict usage of localstorage for node env

src/SASjs.ts, src/SASjsApiClient.ts
no issue to link
Support `SASJS` deployment with authentication
Add AuthConfig as we have for `SASVIYA`
=> fix(SASJS): sasjs server deployment with auth + refresh token bug

package-lock.json, package.json, src/SASjsApiClient.ts, src/types/ExecuteScript.ts, src/utils/parseWeboutResponse.ts
https://github.com/sasjs/cli/issues/1108
- Parse `_webout` response.
- Used ` parseWeboutResponse` utility to parse `_webout`.
Mocked:
Server(without `request.spec.server`):
=> feat(executeJobSASjs): add parse _webout in response

package-lock.json, package.json, src/request/Sas9RequestClient.ts
no issue to link
Issue with `SAS9` deployment
Reverted npm package version of `axios-cookiejar-support` and related changes.
Tested with `SAS9` deployment, it works.
Mocked:
Server (without `request.spec.server`):
Viya:
SAS 9:
Viya:
SAS9:
=> fix: reverted axios-cookiejar-support package

sasjs-tests/src/testSuites/Basic.ts, src/SASjs.ts, src/types/SASjsConfig.ts
none
made pathsasjs attribute of  sasjs config non optional (mandatory)
* remove optional symbol from pathSASJS in sasjs config type
* provided default value for pathSASJS
Mocked:
Server (without `request.spec.server.ts`):
VIYA:
SAS9:
Viya:
SAS9:
=> fix: made pathsasjs non optional in sasjs config

src/job-execution/SasJsJobExecutor.ts, src/job-execution/WebJobExecutor.ts
Related to `SASJS` server, [webout response as json object](https://github.com/sasjs/server/issues/72)
Code crashing while parsing json object, trying to extract webout as if it has string headers `>>weboutBEGIN<<`
Added condition not to parse webout, if it's already an object.
=> fix: no need to parse if webout is an object

src/request/RequestClient.ts
no issue to link.
If `SAS9` deploy fails with error of type `jobExecutionError`. it throws `404` as errorCode to `sasjs/cli`.
And sasjs/cli deals `404` as sasjs_runner issue.
Setting `500` instead of `404` while throwing error.
Mocked:
Server (without `request.spec.server` and `testing.spec.server`):
Viya:
SAS 9:
Viya:
SAS 9:
=> fix: changed return code in case of job execution error

src/job-execution/WebJobExecutor.ts
No issue to link.
Why not returning `log` in response object, `WebJobExecutor`
Added log attribute to return object for `WebJobExecutor`
Mocked:
Server (without `testing.spec.server`):
VIYA:
SAS 9:
Viya:
SAS 9:
=> fix: WebJobExecutor also returns log along result

src/auth/getAccessTokenForViya.ts, src/auth/spec/getAccessTokenForViya.spec.ts
Fixes #660 
Unable to perform `sasjs auth` (exchange of authCode with accessToken/refreshToken) on SASVIYA4
Implemented request with headers based on SASVIYA4 docs.
It also works with SASVIYA3.5:
=> fix(viya): updated getAccessTokenForViya with headers based on latest docs

src/SASViyaApiClient.ts
closes #669 
* As Viya4 provides an incorrect member count, so we set a minimum limit to 500
* if `memberCount` in folder is less than 500 then set limit to 500 else go with `folder.memberCount`
=> fix: Viya 4 provides incorrect memberCount in the folders API

src/job-execution/Sas9JobExecutor.ts
closes #677
* returns a promise from execute method of SAS9JobExecutor.
=> fix: return requestPromise from sas9JobExecutor

package-lock.json, package.json, src/SASjs.ts, src/SASjsApiClient.ts
sasjs/server [issue](https://github.com/sasjs/server/issues/91)
Add stream app related info(streamServiceName, streamWebFolder, streamLogo) in deploy request.
Deploy request to `SASJS` server contains additional body param from `StreamConfig`.
- streamWebFolder
- streamServiceName OPTIONAL <-- server can auto-assign name OR in case of conflict with existing
- streamLogo OPTIONAL <-- server can auto-assign logo
=> feat(deploy): stream app deployment on SASJS server

src/file/generateFileUploadForm.ts
closes #684 
- fix "blob is not defined" in node. This error was occurring in `generateFileUploadForm` function when running in cli.
- remove the creation of blob in cli
- directly append the generated csv string in formData in cli
Mocked:
Server (without `request.spec.server`:
VIYA:
SAS 9:
=> fix: blob is not defined

src/utils/parseViyaDebugResponse.ts
closes #689 
- viya4 returns a bit different iframe than viya 3.5. Adjusted the code to handle both cases.
- used regex instead of simple string to extract JSON URL from the iframe element.
=> fix: update code for extracting JSON URL on viya4 when debug is enabled

src/SASjs.ts, src/SASjsApiClient.ts
none
* execute script on sasjs server
* add a method `executeScript` in `SASjsApiClient` class for executing scripts on sasjs server 
=> feat: add method for executing scripts on sasjs server

src/SASjsApiClient.ts
* we get log in the form of the array when the script is executed on sasjs server
* parse the log to make it a single string
=> fix: parse log in executeScript method on sasjs server

src/SASjs.ts, src/SASjsApiClient.ts, src/job-execution/WebJobExecutor.ts
#703 
When using adapter with Sasjs server type:
- `executeJob` function was missing `authConfig` parameter.
- `request` method wasn't returning error when access token missing - because we use web approach which was waiting on loggin to resend request. Now if callback is not present we don't engage resend requests, we abort execution and return error.
Mocked:
Server:
=> sasjs server type - request and job execution auth fix

src/job-execution/WebJobExecutor.ts, src/request/RequestClient.ts, src/types/errors/InvalidCsrfError.ts
Fixes #711 
- Fix: infinite Promise waiting when webout empty
- Fix: when csrf token expired or not present, re-fetch it automatically.
- Created new error type `InvalidCsrfToken`
- Throwing error when matched
- Re-fetching token and resending request 
=> When expires csrf token, re-fetch and empty webout fix

src/request/RequestClient.ts
closes #730 
* There are some edge cases in which the SAS [mp_abort macro](https://core.sasjs.io/mp__abort_8sas.html) is unable to provide a clean exit.  In this case the JSON response will be wrapped in `>>weboutBEGIN<<` and `>>weboutEND<<` strings.
Therefore, if the first string exists, we won't throw `JobExecutionError` error from `parseError` function in `RequestClient`
* added an additional check to see if `>>weboutBEGIN<<` exists in response data
=> fix: do not throw job execution error if response contains >>weboutBEGIN<<

src/test/utils/formatDataForRequest.spec.ts, src/utils/convertToCsv.ts
#733 
During conversion to CSV, a check is added when an input data value is `special missing`, the dot is not added multiple times. If dot is missing, it will be added.
=> fix: special missing double dot issue

src/request/RequestClient.ts
closes #721 
* When service is not found, service $(program) was not found is being received from the server but it is being interrupted by another error i.e. `response.data.LowerCase` is not a function that is thrown when `response.data` is not a string
* added an additional check for `typeof response.data === 'string'`  
=> fix: add additional check for string type before converting data to lower case

src/auth/AuthManager.ts, src/request/RequestClient.ts, src/types/errors/InvalidCsrfError.ts, src/types/errors/InvalidSASjsCsrfError.ts
Due to change in sasjs/server, [PR](https://github.com/sasjs/server/pull/248)
Need to update adapter behavior
Old Mechanism: makes request to root, and server sets cookie with `Set-Cookie`, and httpClient uses this cookie automatically.
New Mechanism: makes request to root, and server add csrf token to response, adapter creates cookie of it's own and httpClient uses this cookie automatically.
=> fix(server): csrf cookie is created explicitly

src/request/SasjsRequestClient.ts
when `webout` is empty, `parseResponse` method from SasjsRequestClient class throws error
parse webout section only if it's not empty
=> fix: update parse response method of sasjsRequestClient

src/SASjsApiClient.ts
* should not catch an error from executeScript and assign it to `parsedSasjsServerLog`.
* we should let the calling code (cli / vscode) handle the error.
=> fix: should not assign error to parsedSasjsServeLog

README.md
example with label was not correct in read.me
Correct example of label use in webout
changes label to dslabel in %webout example
=> Correted label in read.me to dslabel

src/auth/AuthManager.ts, src/auth/spec/AuthManager.spec.ts, src/types/Login.ts, src/utils/sas9/extractUserLongNameSas9.ts, src/utils/spec/extractUserLongNameSas9.spec.ts
No issue to link.
Cannot fetch username in case of `SAS9`
Added another property `userLongName` to Login Response along `userName`.
Upon login if already loggedIn, returning with that information.
Also renamed `extractUserNameSas9` to `extractUserLongNameSas9` with it's test
=> Introduced user long name

package-lock.json, package.json
* calling checkNodeVersion script in preinstalling and prebuild steps causes some unexpected problems. So ,removed the invocation of this script from the package.json file and rather add a new script that will advise to use node lts version
=> fix: remove the invocation of checkNodeVersion script

sasjs-tests/package-lock.json, sasjs-tests/package.json
* get rid of vulnerabilities 
* npm audit fix
* bump @sasjs/test-framework
* bump node-sass
=> fix: vulnerabilities in sasjs-tests

package-lock.json, package.json, src/SASjsApiClient.ts
`createReadStream` depends on `fs` which is node-specific util, so we import it inside of the node-specific function because importing globally was failing on the Browser environment.
=> fix: createReadStream import where needed

src/request/RequestClient.ts
=> fix: improve error message when sasjs runner is not found

package-lock.json, package.json
closes #771
* current version of axios was causing some problems on latest version of node.
* updated the axios version from 0.26.0 to 0.27.2
=> fix: bump axios version

src/SASjs.ts
Fixes #783
Re-sending the waiting requests function was not called in the `sasjsJobExecutor` 
Added the function call.
No PR (that involves a non-trivial code change) should be merged unless all items below are confirmed!  If an urgent fix is needed - use a tar file.
=> Sasjs executor not re-sending waiting requests

src/auth/AuthManager.ts
Fixes #786
Improving matching string  that removes `.do` from login url, when not `VIYA`
=> fix: removing .do from loginUrl mechanism

src/request/Sas9RequestClient.ts
=> fix: throw error as it is when its an instance of JobExecutionError

src/types/errors/ErrorResponse.ts
Closes #680 
Since the issue was opened a long time ago and quite some stuff changed, I propose that we make this interface public to be available for use in client apps.
This change should not introduce any issues since it is just exporting the interface.
Ideally `details` property in that interface should have a better-defined type than `any`. But for that to be achieved we need to find and change every single place where errors are returned.
We can do it in future, bit by bit, when we find such places while fixing/adding features.
`ErrorBody` in the `ErrorResponse.ts` file exported.
=> ErrorBody interface made public

src/SASViyaApiClient.ts, src/auth/getTokens.ts, src/auth/refreshTokensForViya.ts, src/auth/spec/refreshTokensForViya.spec.ts
Because typeof `FormData` is `function` for node and browser environments, it is right to compare it to `undefined`.
Fix sending form data to `/SASLogon/oauth/token` endpoint in order to refresh access token.
`isNode` utility is used to check if the environment is `node` to use a correct instance of `FormData` from `form-data` package.
=> fix(refreshTokensForViya): fixed FormData logic

webpack.config.js
Fix packaged output file name for Node.
By default, webpack is using `main.js` as a file name which is not correct for this project and results into the following error:
`Error: Cannot find module '@sasjs/adapter/node'`
Explicitly set `filename` in `nodeConfig` of the webpack.
=> fix(packaging): fixed output file for Node

src/SASViyaApiClient.spec.ts, src/SASViyaApiClient.ts, src/SASjs.ts
Closes #245 
Closes #429
- Fix `deployServicePack` when folder/file already exists.
- Improve error message if the folder already exists and `isForsed` is falsy.
- Passed the `isForsed` attribute to the `createFolder` method.
- Handled if `accessToken` is absent.
- Improved error parsing.
- Added unit test.
=> fix(deploy-service-pack): fixed redeployment

src/request/SasjsRequestClient.ts
An empty `WEBOUT` has been incorrectly parsed for `SASJS` server type.
- Improve the `parseResponse` method of the `SasjsRequestClient` class.
- Fixed `webout` type checking in the `parseResponse` method.
=> fix(sasjs-request-client): fixed response parsing

src/job-execution/SasjsJobExecutor.ts
In this commit these lines have been added to parse the json, if response comes in as string, which happens when debug is on. 
https://github.com/sasjs/adapter/commit/2d6efa2437231e5e9a4920ef3a025666d9ef2c32#diff-663fa65ded8381d80ed08a8d0518b473a97b8aec1c135767a988d1579e6cbf85R96-R98
- First issue is `.trim()` function in the condition, if the response is of a type `object` it will fail because `trim()` is not a function that exists inside.
- Second issue is `{ result } = res.result` that will resolve as `res.result.result` which is one level too deep. 
- (CI Runs this) All `sasjs-tests` are passing. If you want to run it manually …
=> fix: issue with parsing json in sasjs job executor

.github/workflows/generateDocs.yml, .github/workflows/npmpublish.yml
- Use the same Node version in all CI/CD workflows.
- Used `lts/hydrogen` in `.github/workflows/generateDocs.yml` and `.github/workflows/npmpublish.yml`.
=> chore(ci-cd): used Node lts/hydrogen version

sasjs-tests/package-lock.json
- Bump dependencies in `sasjs-tests`.
- Bumped `webpack`.
- Bumped `http-cache-semantics`.
- Bumped `json5`.
- Bumped `loader-utils`.
- Bumped `semver-regexp`.
=> Dependencies bump

src/SASjs.ts, src/request/RequestClient.ts, src/test/RequestClient.spec.ts
This feature has been added to support https://github.com/sasjs/cli/issues/1356.
- Add a method that intercepts every HTTP response and logs its summary.
- Add a method that disables HTTP response interception.
- Added `enableVerboseMode` method to `RequestClient` class.
- Added `disableVerboseMode` method to `RequestClient` class.
- Added `defaultInterceptionCallBack` method to `RequestClient` class.
=> feat(request-client): implemented verbose mode

README.md, src/SASjs.ts, src/minified/sas9/SASjs.ts, src/minified/sas9/WebJobExecutor.ts, src/request/RequestClient.ts, src/types/SASjsConfig.ts
- Add `verbose` option to `sasjsconfig`.
- Add public methods to enable/disable verbose mode.
- Changed the constructor method of `RequestClient` to make verbose mode configurable when an instance of `RequestClient` is instantiated.
- Added `enableVerboseMode` and `disableVerboseMode` public methods to `src/SASjs.ts`.
- Updated `README.md`.
=> feat(request-client): made verbose mode easier to configure

.github/workflows/assign-reviewer.yml, .github/workflows/generateDocs.yml, .github/workflows/npmpublish.yml
- Use `GITHUB_TOKEN` as an access token in github actions.
- Updated `.github/workflows/assign-reviewer.yml`.
- Updated `.github/workflows/generateDocs.yml`.
- Updated `.github/workflows/npmpublish.yml`.
=> chore(gh-action): fixed access token

.github/PULL_REQUEST_TEMPLATE.md, jest.config.js, src/SASjs.ts, src/api/viya/executeScript.ts, src/request/RequestClient.ts, src/test/RequestClient.spec.ts
Related issue https://github.com/sasjs/cli/issues/1367
- Handle HTTP responses with any status when `RequestClient` is in verbose mode.
- Added logic to handle `AxiosError` in `defaultInterceptionCallBack` method with fallback options.
- Covered `defaultInterceptionCallBack` method with unit tests mocking responses with random statuses from `1**` to `5**`.
- Fixed typo in `src/api/viya/executeScript.ts`.
- Set unit test coverage threshold and updated `.github/PULL_REQUEST_TEMPLATE.md`.
- (CI Runs this) All `sasjs-tests` are passing. If you want to run it manually (instructions available …
=> Fixed verbose mode for all response statuses

jest.config.js, src/SASViyaApiClient.ts, src/api/viya/executeOnComputeApi.ts, src/api/viya/executeScript.ts, src/api/viya/spec/executeScript.spec.ts
Closes #829 
- Job arguments don't make sense during the execution of a SAS job using compute API and should not be part of the request body.
- Renamed `executeScript` to `executeOnComputeApi`.
- Removed `jobArguments` from the request body in `src/api/viya/executeOnComputeApi.ts`.
- Adjusted unit tests in `src/api/viya/spec/executeScript.spec.ts`.
=> fix(execute-script): fixed executing jobs on viya using compute api

jest.config.js, src/api/viya/pollJobState.ts, src/api/viya/spec/pollJobState.spec.ts
Parent session may be in a not healthy state (`running` or `idle`) while checking SAS job state.
- Add `idle` as a healthy parent session state.
- Added `isSessionStatesHealthy` utility to  `src/api/viya/pollJobState.ts`.
- Adjusted unit tests covering `doPoll` function.
=> fix(poll-job-state): fixed checking session state

.github/workflows/build.yml, src/auth/AuthManager.ts, src/auth/spec/AuthManager.spec.ts
- The `SASLogon` URL is incorrect when the login mechanism is `Redirected`.
- Add server URL to redirected login URL.
- Added `serverUrl` to `redirectedLoginUrl` in `src/auth/AuthManager.ts`.
=> fix(auth-manager): fixed redirectedLoginUrl

package-lock.json, package.json
Addressing `form-data` critical vulnerability
=> Update vulnerable form-data to v4.0.4
