src/SASjs.ts
src/utils/isIeOrEdge.ts

Fixes inconsistent behaviour between Edge versions, Firefox and IE11.

fix(*): use fetch polyfill in IE, Edge and Firefox <60

---

src/SASViyaApiClient.ts

Fetch log only when debug is switched on.
* Fixed condition to use `debug` flag.

fix(logs): fetch log only when debug is switched on

---

CONTRIBUTING.md
sasjs-tests/README.md
sasjs-tests/package-lock.json
sasjs-tests/package.json

* Added instructions for running tests.
* Added instructions for creating tests.
* Added NPM scripts for building and deploying `sasjs-tests`.

chore(*): update documentation, bump adapter version

---

src/SASjs.ts

fix: executeJobViaWeb retry requests missing params

---

.github/workflows/build.yml

Closes https://github.com/sasjs/adapter/issues/76.

chore(ci): run unit tests as part of build

---

src/SASViyaApiClient.ts
src/SASjs.ts

* Changed public functions to take `contextName`.
* Fetch original context by name.
* Fetch context by ID so that the `etag` and all other properties are available to update.
* Update context by ID.

feat(update-context): Allow updating of a context by name

---

src/SASViyaApiClient.ts
src/SASjs.ts
src/utils/makeRequest.ts

fix: running request with access_token fails

---

src/SASViyaApiClient.ts
src/utils/makeRequest.ts

fix(error): added error handling for http responses with status 401 and 403

---

src/SASViyaApiClient.ts
src/SASjs.ts

https://github.com/sasjs/cli/issues/73
Make methods related to folder management publicly available.
Updated 'SASjs' class and fixed logic in 'SASViyaApiClient'.

feat(folder-management): made folder related methods public

---

src/utils/makeRequest.ts

closes #114 
Update error message.

chore(error-message): updated error message for forbidden request

---

src/SASViyaApiClient.ts
src/SASjs.ts
src/SessionManager.ts

Fixes https://github.com/sasjs/adapter/issues/119
Pass down `debug` value from SASjs config into `SASViyaApiClient` and `SessionManager`.
* Created `debug` instance property on `SASViyaApiClient` and `SessionManager`.
* Set `debug` value whenever the top level value changes.
* Removed unused method `waitForSession`.

fix(debug): propagate debug value from SASjs config

---

src/SASViyaApiClient.ts

closes #124
Fix fetching executable contexts.
Fixed 'getExecutableContexts' method.

fix(context): fixed 'getExecutableContexts' method

---

src/SASViyaApiClient.ts

Safely handle cases when `code` was not provided to `executeComputeJob` method.
Updated `executeComputeJob` method of `SASViyaApiClient` class.

fix(executeComputeJob): added fix for cases when code was not provided

---

src/SASjs.ts

Safely handle cases when `location` was not defined.
1. Changed `setupConfiguration` method.

fix(location): added handle cases when 'location' is not defined

---

src/SASViyaApiClient.ts
src/SASjs.ts
src/types/ErrorResponse.ts

Closes #113 
Handle the error when requested service is not found using the ErrorResponse class.

feat: service not found error handling

---

PULL_REQUEST_TEMPLATE.md
src/SASViyaApiClient.ts

Fix context processing issue.
Changed SAS response parsing.

fix(context): fixed log parsing

---

src/SASViyaApiClient.ts

Fix `getExecutableContexts` method.

fix(context): fixed result parsing

---

.gitignore
package.json

BREAKING CHANGE: SASjs Adapter 2.0 - Electric Boogaloo
1. Bump SASjs Adapter version.
2. Enable gathering test coverage.

test(coverage): enabled gathering coverage

---

src/SASViyaApiClient.ts
src/SessionManager.ts

Prevent multiple logging.
- Updated `SessionManager` 
- Updated `SASViyaApiClient`

feat(*): improved session and job logging

---

src/SASViyaApiClient.ts

Remove unnecessary catch block.

chore(error-handling): removed redundant catch block

---

sasjs-tests/package-lock.json
sasjs-tests/package.json
sasjs-tests/public/config.json
sasjs-tests/src/testSuites/Basic.ts

Written tests covering the #258 
`sasjs-tests`
(Didn't change any functionality code)

test: issue 258

---

src/test/utils/isUrl.spec.ts
src/utils/isUrl.ts

closes #325 
Improve url validation

fix(utility): improved 'isUrl' utility

---

src/job-execution/JesJobExecutor.ts

Provide log in response of the `sasjs.request` method.
Mocked:
Server:

fix(request): returned response with log

---

.npmignore
CHANGELOG.md
LICENSE
README.md
package.json

Updates to metadata only.  Addition of a .npmignore file should reduce bundle size significantly.

Qualityfixes

---

package.json

fixing incorrect change to package.json

fix: metadata in package.json

---

README.md

fix: readme badges

---

.github/reviewer-lottery.yml

Add Sabir to list of dev reviewers, create separate QA list with Vlad

chore(reviewers): add Sabir and Vlad as reviewers

---

src/SASViyaApiClient.ts

Fixes https://github.com/sasjs/adapter/issues/460.
Fix adapter not working with Angular apps.
* Imported `@sasjs/utils` functions from separate paths.
The below items are not impacted by this fix and so have not been tested.

fix(imports): change imports from main barrel into internal barrels

---

sasjs-tests/README.md
sasjs-tests/package.json

Supporting windows machine sasjs-tests deploy.
No code changed.

Windows tests

---

src/api/viya/pollJobState.ts

https://github.com/sasjs/cli/issues/587
Use default poll options and override with supplied ones.
Poll at short intervals for the first 100 times.
* Added `defaultPollOptions`, merged with `pollOptions` passed in.
* Added comments to make the intent clear.
Tested against https://github.com/sasjs/cli/pull/849
-Mocked Tests 
- Server Tests

fix(poll): add default poll options

---

src/FileUploader.ts
src/SASjs.ts
src/job-execution/JobExecutor.ts
src/job-execution/WebJobExecutor.ts
src/request/RequestClient.ts
src/test/FileUploader.spec.ts

No issue to link
Improve code and stick to standards followed in other sections of codebase. 
Mocked:
Server:
VIYA:
SAS9:
VIYA:
SAS9:

chore(imprvements): code changes for fileUploader

---

package-lock.json
sasjs-tests/package.json

No issue to be linked
Updating test-framework to the newest version (fixed high cpu usage)
Tested on Viya (windows):
Tested on SAS9 (windows):

chore: bump up test-framework

---

src/SASjs.ts
src/job-execution/Sas9JobExecutor.ts

Fixes #588 
- sas9JobExecutor not returning responses
- sas9JobExecutor not appending requests to SasRequests
Mocked:
Server:
SAS VIYA:
SAS9:

fix: sas9JobExecutor issues

---

src/SASjs.ts
src/auth/AuthManager.ts
src/job-execution/WebJobExecutor.ts
src/types/SASjsConfig.ts
src/utils/getValidJson.ts
src/utils/parseWeboutResponse.ts

Link any related issue(s) in this section.
Mocked:
Server:
Viya
Sas9

fix: handle sasjs server response

---

sasjs-tests/README.md

#607 
enable test suite to support special missings
added missing param to macro invocation

chore(readme): support for special missings

---

sasjs-tests/src/testSuites/SpecialCases.ts
src/file/generateFileUploadForm.ts
src/file/spec/generateFileUploadForm.spec.ts
src/utils/convertToCsv.ts

Closes #624
- Fix special missing values support in `request` method.
- Fixed sending format object to `convertToCSV` utility.
Mocked:
Server (without `request.spec.server`):
Viya:
SAS9:
Viya:
SAS9:

fix(special-missing): fix convertToCSV format object

---

src/job-execution/SasJsJobExecutor.ts
src/job-execution/WebJobExecutor.ts

[sasje/server](https://github.com/sasjs/server/issues/68)

fix: adopted new log structure of SASJS server

---

src/SASjsApiClient.ts
src/request/RequestClient.ts

Link any related issue(s) in this section.

fix: added additional params to axios POST while deploy to SASJS server

---

src/job-execution/WebJobExecutor.ts
src/utils/getValidJson.ts

Link any related issue(s) in this section.

fix: not to use NodeFormData function on web

---

package-lock.json
package.json
sasjs-tests/README.md
sasjs-tests/package-lock.json
sasjs-tests/src/testSuites/SpecialCases.ts
src/api/viya/uploadTables.ts
src/file/generateFileUploadForm.ts
src/file/generateTableUploadForm.ts
src/job-execution/Sas9JobExecutor.ts
src/utils/convertToCsv.spec.ts
src/utils/convertToCsv.ts
src/utils/formatDataForRequest.ts

Support special missing values on Viya and SAS9.
- Added new test cases to `sasjs-tests/src/testSuites/SpecialCases.ts`.
- Refactored `convertToCSV` to look for formats object internally.
Mocked:
Server:
SAS 9:
Viya:

fix: special missing values

---

package-lock.json
package.json
src/test/utils/formatDataForRequest.spec.ts
src/utils/convertToCsv.ts

When converting to CSV the adapter does a `sas special missing` check. To prevent duplicate code across repositories, we import that utility function check from @sasjs/utils.

Special missing function from @sasjs/utils

---

src/utils/convertToCsv.ts

- Remove debugging `console.log`.

chore: removed console.log

---

README.md

bumping a release with README updates

fix: bumping with README updates

---

.github/workflows/npmpublish.yml

- Fix `npmpublish` workflow.
- Added `actions/setup-node@v2` to `npmpublish.yml`.

fix(workflow): added actions/setup-node@v2

---

src/request/RequestClient.ts

#741 
- When debug is on and SAS9 returns JSON instead of text response `appendRequest` was failing.

fix: error when multiple redirections happen while debug is on

---

.github/workflows/generateDocs.yml

* add proper indentation in workflow file

chore: fix workflow syntax

---

.github/workflows/npmpublish.yml

n/a
Update github action to post to matrix instead of slack
Change to deployment yaml file only

chore: moving slack message to matrix

---

src/SASjsApiClient.ts

* add a method in the sasjsAPI client to deploy service packed zip file to sasjs server

feat: add a new method deployZipFile in sasjsAPiClient class

---

package-lock.json
package.json
src/auth/AuthManager.ts
src/auth/isLoginRequired.ts
src/types/Login.ts

closes #303
closes #789
* write a message to the log indicating that a login was not attempted as a valid session already exists.
* Also fix login issues on latest sas9

fix: modify the regex to handle the loginForm response on latest sas9

---

src/auth/AuthManager.ts

closes #470 
could not reproduce the bloating issue (#470)

fix: regex for extracting login url fixed

---

.github/vpn/config.ovpn
.github/workflows/build.yml
cypress/integration/sasjs.tests.ts
cypress/support/commands.js
cypress/support/index.js
package-lock.json
package.json
sasjs-tests/.gitignore
sasjs-tests/package-lock.json
sasjs-tests/public/config.json
sasjs-tests/sasjs-cypress-run.sh
sasjs-tests/sasjs/sasjsconfig.json

chore(ci): install vpn and run sasjs tests
